import { DemoScenario } from './types';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    name: '✅ Low Risk: Standard Payroll',
    description: 'Regular payroll transfer from US company to Singapore employee',
    expectedRisk: 'low',
    input: {
      amount: 3500,
      currency: 'USD',
      sourceJurisdiction: 'United States',
      destinationJurisdiction: 'Singapore',
      purpose: 'Payroll',
      counterpartyType: 'Individual Freelancer',
      counterpartyName: 'John Smith',
      isNewCustomer: false,
      isPEP: false,
      frequencySignals: 'Regular monthly pattern',
      additionalNotes: 'Monthly salary payment to remote developer',
    },
  },
  {
    name: '⚠️ Medium Risk: E-commerce B2B',
    description: 'Business payment from Philippines SMB to Thailand supplier',
    expectedRisk: 'medium',
    input: {
      amount: 15000,
      currency: 'USD',
      sourceJurisdiction: 'Philippines',
      destinationJurisdiction: 'Thailand',
      purpose: 'Trade Finance',
      counterpartyType: 'Small Business (SMB)',
      counterpartyName: 'Thai Supplies Co.',
      isNewCustomer: true,
      isPEP: false,
      frequencySignals: 'First transaction',
      additionalNotes: 'Inventory purchase for e-commerce business',
    },
  },
  {
    name: '🔴 High Risk: Offshore Investment',
    description: 'Large investment transfer from Nigeria to Cayman Islands shell company',
    expectedRisk: 'high',
    input: {
      amount: 75000,
      currency: 'USDC',
      sourceJurisdiction: 'Nigeria',
      destinationJurisdiction: 'Cayman Islands',
      purpose: 'Investment',
      counterpartyType: 'Shell Company',
      counterpartyName: 'Global Holdings Ltd.',
      isNewCustomer: true,
      isPEP: true,
      frequencySignals: 'Multiple sub-10k transfers in 24h',
      additionalNotes: 'Investment in offshore fund structure',
    },
  },
  {
    name: '🔴 High Risk: Structuring Pattern',
    description: 'Multiple small transfers just under reporting threshold',
    expectedRisk: 'high',
    input: {
      amount: 9500,
      currency: 'USD',
      sourceJurisdiction: 'Russia',
      destinationJurisdiction: 'UAE',
      purpose: 'Crypto Trading',
      counterpartyType: 'Crypto Exchange',
      counterpartyName: 'Unknown Exchange',
      isNewCustomer: true,
      isPEP: false,
      frequencySignals: 'Multiple sub-10k transfers in 24h',
      additionalNotes: 'Third transfer today, all near $9,500',
    },
  },
  {
    name: '⚠️ Medium Risk: Cross-border Remittance',
    description: 'Family remittance from Singapore to Philippines',
    expectedRisk: 'medium',
    input: {
      amount: 2000,
      currency: 'SGD',
      sourceJurisdiction: 'Singapore',
      destinationJurisdiction: 'Philippines',
      purpose: 'Remittance',
      counterpartyType: 'Individual Freelancer',
      counterpartyName: 'Maria Santos',
      isNewCustomer: false,
      isPEP: false,
      frequencySignals: 'Regular monthly pattern',
      additionalNotes: 'Monthly family support remittance',
    },
  },
  {
    name: '🔴 Critical: PEP Gambling Transfer',
    description: 'PEP transferring to gambling platform from sanctioned region',
    expectedRisk: 'high',
    input: {
      amount: 50000,
      currency: 'USDT',
      sourceJurisdiction: 'Venezuela',
      destinationJurisdiction: 'Malta',
      purpose: 'Gambling',
      counterpartyType: 'Unknown/Unverified',
      counterpartyName: 'Casino Platform International',
      isNewCustomer: true,
      isPEP: true,
      frequencySignals: 'Sudden increase in transaction volume',
      additionalNotes: 'Online gambling platform deposit',
    },
  },
];
